// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: producer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducerServiceClient is the client API for ProducerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerServiceClient interface {
	StreamProducer(ctx context.Context, opts ...grpc.CallOption) (ProducerService_StreamProducerClient, error)
}

type producerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerServiceClient(cc grpc.ClientConnInterface) ProducerServiceClient {
	return &producerServiceClient{cc}
}

func (c *producerServiceClient) StreamProducer(ctx context.Context, opts ...grpc.CallOption) (ProducerService_StreamProducerClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProducerService_ServiceDesc.Streams[0], "/producer.ProducerService/StreamProducer", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerServiceStreamProducerClient{stream}
	return x, nil
}

type ProducerService_StreamProducerClient interface {
	Send(*MainProducerRequest) error
	Recv() (*MainProducerResponse, error)
	grpc.ClientStream
}

type producerServiceStreamProducerClient struct {
	grpc.ClientStream
}

func (x *producerServiceStreamProducerClient) Send(m *MainProducerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerServiceStreamProducerClient) Recv() (*MainProducerResponse, error) {
	m := new(MainProducerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProducerServiceServer is the server API for ProducerService service.
// All implementations must embed UnimplementedProducerServiceServer
// for forward compatibility
type ProducerServiceServer interface {
	StreamProducer(ProducerService_StreamProducerServer) error
	mustEmbedUnimplementedProducerServiceServer()
}

// UnimplementedProducerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProducerServiceServer struct {
}

func (UnimplementedProducerServiceServer) StreamProducer(ProducerService_StreamProducerServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamProducer not implemented")
}
func (UnimplementedProducerServiceServer) mustEmbedUnimplementedProducerServiceServer() {}

// UnsafeProducerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServiceServer will
// result in compilation errors.
type UnsafeProducerServiceServer interface {
	mustEmbedUnimplementedProducerServiceServer()
}

func RegisterProducerServiceServer(s grpc.ServiceRegistrar, srv ProducerServiceServer) {
	s.RegisterService(&ProducerService_ServiceDesc, srv)
}

func _ProducerService_StreamProducer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServiceServer).StreamProducer(&producerServiceStreamProducerServer{stream})
}

type ProducerService_StreamProducerServer interface {
	Send(*MainProducerResponse) error
	Recv() (*MainProducerRequest, error)
	grpc.ServerStream
}

type producerServiceStreamProducerServer struct {
	grpc.ServerStream
}

func (x *producerServiceStreamProducerServer) Send(m *MainProducerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerServiceStreamProducerServer) Recv() (*MainProducerRequest, error) {
	m := new(MainProducerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProducerService_ServiceDesc is the grpc.ServiceDesc for ProducerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "producer.ProducerService",
	HandlerType: (*ProducerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProducer",
			Handler:       _ProducerService_StreamProducer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "producer.proto",
}
