version: '3.9'
services:
  customer4_backend:
    restart: always
    container_name: customer4_backend
    build: .
    expose:
      - 50054
    networks: 
      - service_demo
    volumes:
      - .:/app

networks:
  service_demo:
    name: net-service-demo