version: '3.9'
services:
  customer1_backend:
    restart: always
    container_name: customer1_backend
    build: .
    expose:
      - 50051
    networks: 
      - service_demo
    volumes:
      - .:/app

networks:
  service_demo:
    name: net-service-demo