version: '3.9'
services:
  customer5_backend:
    restart: always
    container_name: customer5_backend
    build: .
    expose:
      - 50055
    networks: 
      - service_demo
    volumes:
      - .:/app

networks:
  service_demo:
    name: net-service-demo