version: '3.9'
services:
  customer3_backend:
    restart: always
    container_name: customer3_backend
    build: .
    expose:
      - 50053
    networks: 
      - service_demo
    volumes:
      - .:/app

networks:
  service_demo:
    name: net-service-demo